### ISSUE TITLE
wrf2rev scripts missing from repo

### ISSUE THREAD

**Issue by sschrei** [GODEEEP/tgw-gen#1]
I am trying to use this package to learn more about generating h5 files for use in reV, as well as create some wind generation profiles for select locations using this data. The README references several files/folders that appear to be missing, including "wrf2rev_*.py" and "data/sam_resource/". Is the README outdated, or am I otherwise missing something?

**Comment by cameronbracken** [comment]
Sorry the documentation is out of date, apologies. But you'll want to look at `rev_solar.py` or `rev_wind.py` to see how to take gridded climate model data and set up an hdf5 file for use with reV.

**Comment by sschrei** [comment]
Thank you! I will close this for now but follow up if I run into additional issues or have further questions.
